# Plot the infectivity curves of STIs
# (data file generated by C++ code in CODECHECK_STI_infectivity_curves)

library(ggplot2)
theme_set(theme_bw())

getScriptPath <- function(){
  cmd.args <- commandArgs()
  m <- regexpr("(?<=^--file=).+", cmd.args, perl=TRUE)
  script.dir <- dirname(regmatches(cmd.args, m))
  if(length(script.dir) == 0) stop("can't determine script dir: please call the script with Rscript")
  if(length(script.dir) > 1) stop("can't determine script dir: more than one '--file' argument detected")
  return(script.dir)
}

setwd(getScriptPath())


### Retrieve data generated by C++ model

dat <- read.csv("./codecheck_STI_IC.out",header=FALSE)
colnames(dat) <- c("STI","time","IC")

### Generate plots of all infectivity curves

pdf("codecheck_STI_IC.pdf",width=15,height=20)

dat$STI2 <- substr(dat$STI,1,2)

g <- ggplot(dat) + geom_ribbon(aes(x=time,ymin=0,ymax=IC,fill=STI2),
                               lwd=1,
                               colour="gray",
                               alpha=0.5) 
g <- g + facet_wrap(~STI,scales="free_x")
g <- g + ggtitle("STI Infectivity Curves")+xlab("Time (years)")
print(g)

dev.off()
